[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "YAW Code and Data Appendix"
author = "YAW Authors"
maintainer = "YAW Authors"
description="Isaac Lab implementation of predictive reward composition for wheel-legged locomotion."
repository = "https://github.com/LexYoung2005/yaw_bot"
keywords = ["isaaclab", "reinforcement-learning", "balancing-robot", "yaw-bot"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "yaw_bot"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
