#!/usr/bin/env python3
"""Fail if the public release is incomplete or leaks machine-local data."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEXT_SUFFIXES = {
    ".cfg",
    ".csv",
    ".json",
    ".md",
    ".py",
    ".rst",
    ".sh",
    ".toml",
    ".txt",
    ".urdf",
    ".yaml",
    ".yml",
}
FORBIDDEN_PARTS = {
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    "logs",
    "outputs",
    "artifacts",
}
FORBIDDEN_SUFFIXES = {".pt", ".pth", ".ckpt", ".pyc"}
LEAK_PATTERNS = {
    "Linux home path": re.compile("/" + r"home/[^/\s]+/"),
    "macOS home path": re.compile("/" + r"Users/[^/\s]+/"),
    "e-mail address": re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.IGNORECASE),
    "asset-generation timestamp": re.compile(
        r"Generated by \S+ on \d{4}-\d{2}-\d{2}",
        re.IGNORECASE,
    ),
}
REQUIRED = {
    "README.md",
    "README_cn.md",
    "LICENSE",
    "NOTICE.md",
    "PAPER_CODE_MAP.md",
    "RELEASE_CHECKLIST.md",
    "configs/paper_experiments.json",
    "configs/environment.json",
    "configs/reward_terms.json",
    "configs/task_interface.json",
    "PROTOCOL_NOTES.md",
    "scripts/reproduce.py",
    "scripts/plot_training_curves.py",
    "scripts/plot_composer_weights.py",
    "scripts/plot_results.py",
    "scripts/export_training_curves.py",
    "scripts/rsl_rl/train.py",
    "scripts/rsl_rl/play.py",
    "source/yaw_bot/yaw_bot/tasks/direct/yaw_bot/yaw_bot_env.py",
    "source/yaw_bot/yaw_bot/tasks/direct/yaw_bot/outer_advantage_composer.py",
    "results/evaluation_aggregate.csv",
    "results/evaluation_per_seed.csv",
    "results/training_per_seed.csv",
    "results/composer_weight_evolution_summary.csv",
    "results/submitted_training_curves.npz",
    "results/README.md",
}


def main() -> None:
    errors: list[str] = []
    files = [
        path
        for path in ROOT.rglob("*")
        if path.is_file() and ".git" not in path.relative_to(ROOT).parts
    ]
    relative_files = {path.relative_to(ROOT).as_posix() for path in files}
    missing = sorted(REQUIRED - relative_files)
    if missing:
        errors.append(f"missing required files: {missing}")

    for path in files:
        relative = path.relative_to(ROOT)
        if any(part in FORBIDDEN_PARTS for part in relative.parts):
            errors.append(f"generated/private directory included: {relative}")
        if path.suffix.lower() in FORBIDDEN_SUFFIXES:
            errors.append(f"generated checkpoint/cache included: {relative}")
        if path.suffix.lower() not in TEXT_SUFFIXES and path.name not in {
            ".gitignore",
            ".asset_hash",
        }:
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for label, pattern in LEAK_PATTERNS.items():
            if pattern.search(content):
                errors.append(f"{label} in {relative}")

    extension = (ROOT / "source/yaw_bot/config/extension.toml").read_text(encoding="utf-8")
    if 'author = "YAW Authors"' not in extension:
        errors.append("extension author metadata is not the public YAW identity")

    evaluation_files = sorted((ROOT / "results/evaluation_json").glob("*.json"))
    if len(evaluation_files) != 18:
        errors.append(f"expected 18 per-seed evaluation JSON files, found {len(evaluation_files)}")
    for path in evaluation_files:
        content = path.read_text(encoding="utf-8")
        if "ANONYMIZED_SELECTED_CHECKPOINT/" not in content:
            errors.append(f"evaluation checkpoint path is not release-safe: {path.relative_to(ROOT)}")

    if errors:
        raise SystemExit("Public-release validation failed:\n- " + "\n- ".join(errors))
    print(f"Public-release validation passed ({len(files)} files).")


if __name__ == "__main__":
    main()
